data = load("measurements.txt");
figure;
plot (data (:,2),"-k;number of macros;");
hold on;
plot (data (:,10), "-g;first-timers;"); 
hold on;
plot (data (:,11),"-b;covered;");
hold on;
plot (data (:,12), "-r;gaed;"); 
hold on;
plot (data (:,13), "-c;inited;"); 
hold on;
plot (data (:,14), "-c;number of classifiers;"); 
hold on;
plot (data (:,18), "-m;correct set population;"); 
grid;
print -color main.jpg;
figure;
plot (data (:,15), "-r;deleted by ns * <F> / f;"); 
hold on;
plot (data (:,16), "-g;deleted by ns;"); 
hold on;
plot (data (:,17), "-b;subsumptions;"); 
grid;

print -color deletions.jpg;
